name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres15:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testingpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5415:5432
      postgres14:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: testingpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5414:5432
      postgres13:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: testingpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5413:5432
      postgres12:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: testingpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5412:5432
      postgres11:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: testingpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5411:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Setup Golang caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - name: Build
      run: go build -v ./...

    - name: Test on PostgreSQL 15
      run: go test -v ./...
      env:
        TESTING_DSN: host=localhost port=5415 user=postgres password=testingpassword

    - name: Test on PostgreSQL 14
      if: always()
      run: go test -v ./...
      env:
        TESTING_DSN: host=localhost port=5414 user=postgres password=testingpassword

    - name: Test on PostgreSQL 13
      if: always()
      run: go test -v ./...
      env:
        TESTING_DSN: host=localhost port=5413 user=postgres password=testingpassword

    - name: Test on PostgreSQL 12
      if: always()
      run: go test -v ./...
      env:
        TESTING_DSN: host=localhost port=5412 user=postgres password=testingpassword

    - name: Test on PostgreSQL 11
      if: always()
      run: go test -v ./...
      env:
        TESTING_DSN: host=localhost port=5411 user=postgres password=testingpassword
